### ISSUE TITLE
Multiple servers

### ISSUE THREAD

**Issue by zawilliams** [wrklst/pulse-remote-server#2]
Hey @tobiasvielmetter - is there a way to add multiple servers? I'm trying to add my cache server and my database server and if I add multiple `\WrkLst\Pulse\RemoteServer\Recorders\RemoteServers::class` entries to the array, they just get overwritten by the last one.

Does this just work with a single remote server?

**Comment by tobiasvielmetter** [comment]
Aparently I have an issue that does not allow for multiple servers yet. If you check this fork for my package, you'll see a solution that works with multiple servers: https://github.com/wrklst/pulse-remote-server/commit/ee832843717026b327789680a9fb633469d8ac4b

I might be able to work on a PR next week to fix this. If you are able and feel like it, feel free to submit a PR solving this according to the reference in the fork.

Thanks

**Comment by tobiasvielmetter** [comment]
actually, check out https://github.com/wrklst/pulse-remote-server/releases/tag/v0.2.6 - I have added this functionality. I have just tested it with a single server. Can you check it out for your setup and if it works fine for multiple servers?

**Comment by zawilliams** [comment]
Sweet - just tried it and seems to be working well! Thanks for bringing that in!
